### ISSUE TITLE
Media parsing is broken as of June 1 2016

### ISSUE THREAD

**Issue by MHova** [prowdsponsor/ig#24]
Instagram rolled out the new version of their API yesterday June 1 2016. In particular, they rolled out the following breaking [change] (https://www.instagram.com/developer/changelog/):

> API responses containing media objects no longer return the data field in comments and likes nodes

This breaks Aeson parsing of the `Media` type, specifically the `mComments` and `mLikes` fields. The `Collection` wrapper expects a `data` json array which no longer exists. The `comments` and `likes` nodes now only contain a `count` field.

**Comment by cdepillabout** [comment]
Closed in #25.
